#User Configuration

#OE_TERMINAL = "tmux"

IMAGE_BOOT_FILES_zynqmp = "BOOT.BIN boot.scr Image ramdisk.cpio.gz.u-boot rootfs.cpio.gz.u-boot"
DISTRO_FEATURES_append = " systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
INIT_MANAGER = "systemd"
SIGGEN_UNLOCKED_RECIPES += "run-postinsts"
