#!/bin/sh
#
# Set the hostname
#


source /etc/init.d/start_only.sh

# Update the hostname after copying/moving files from the SD card
/bin/hostname -F /etc/hostname
# Restart avahi-daemon if it exists to update the hostname
if [ -f /etc/init.d/avahi-daemon ];
then
	/etc/init.d/avahi-daemon stop
	/etc/init.d/avahi-daemon start
fi

