#!/bin/sh
#
# Restores SSH keys from the SD card
#

source /etc/bootvars.conf

source /etc/init.d/start_only.sh

if [ "$_SYS_PERSISTENT_FILESYSTEM" == "true" ]; then
    UPDATE=mv
else
    UPDATE=cp
fi

SD_KEYDIR=${_SD_ROOT}/sshkeys
ETC_KEYDIRS="/etc/ssh /etc/dropbear"

if [ -d $SD_KEYDIR ]; then
	echo -n "### Restoring SSH keys from the SD card to $d "
	for d in $ETC_KEYDIRS ; do
		KEYFOLDER=$SD_KEYDIR/$(basename $d)
		if [ -f $KEYFOLDER/*host_*key* ]; then
        		echo -n "### Restoring keys from the SD card to $d "
        		${UPDATE} -f $KEYFOLDER/*host_*key* $d/
        		chmod 600 $d/*host_*key*
		fi
	        if [ "$_SYS_PERSISTENT_FILESYSTEM" == "true" ]; then
                	rm -rf $SD_KEYDIR
        	fi
	done
	echo "OK"
fi

exit 0

